### ISSUE TITLE
Error on Win 10

### ISSUE THREAD

**Issue by maku** [Microsoft/TypeScript-Node-Starter#1]
On Win 10 I get an error when I run "npm start"

```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! express-typescript-starter@0.1.0 watch: `concurrently -k -p "[{name}]" -n "Sass,TypeScript,Node" -c "yellow.bold,cyan.bold,green.bold" "npm run watch-sass" "npm run watch-ts" "nodemon dist/server.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the express-typescript-starter@0.1.0 watch script 'concurrently -k -p "[{name}]" -n "Sass,TypeScript,Node" -c "yellow.bold,cyan.bold,green.bold" "npm run watch-sass" "npm run watch-ts" "nodemon dist/server.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the express-typescript-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently -k -p "[{name}]" -n "Sass,TypeScript,Node" -c "yellow.bold,cyan.bold,green.bold" "npm run watch-sass" "npm run watch-ts" "nodemon dist/server.js"

```

**Comment by DomDumont** [comment]
Hi, I think I have this error also on windows 7. In my case, it was because nodemon was not installed on my machine, it works now with this command ; "npm install -g nodemon". I think this should be added somewhere in the readme file.

**Comment by bowdenk7** [comment]
Thanks @DomDumont, I added nodemon as a devDependency. Global install works too, but I'm trying to keep manual setup as lean as possible.

@maku can you pull and run `npm install` again and let me know if this resolves your problem?

Thanks again!

**Comment by maku** [comment]
@bowdenk7 this works for me now.

But at first, it seems I cloned the wrong project -> I followed the readme (git clone --depth=1 https://github.com/bowdenk7/express-typescript-starter.git <project_name>) and I didn't recognize that this points to a wrong project....

This seems like an error in the readme.

Now I tried it with the a clone of the correct project and it works for me.

**Comment by bowdenk7** [comment]
Oh wow, sorry I missed that @maku. Thanks for the heads up!
