### ISSUE TITLE
Dev Dependencies section in README file there's some items that has a wrong description

### ISSUE THREAD

**Issue by raerpo** [Microsoft/TypeScript-Node-Starter#10]
First of all, great work with this project by the way. Its been so helpful in my way to learn typescript.
now...
In the #devdepencies-1 section of the README, some items has a wrong description.

jest	-> Reports real-time server metrics for Express.
node-sass -> GitHub API library.
ts-test -> Instagram API library.

I take the liberty of open a PR to solved this.

Thanks!

**Comment by bowdenk7** [comment]
Fixed by #30
