### ISSUE TITLE
WARN invalid config loglevel="notice"

### ISSUE THREAD

**Issue by RevealedFrom** [Microsoft/TypeScript-Node-Starter#115]
Each of the four steps in the npm run script for `build` generates a:

>npm WARN invalid config loglevel="notice"

Where can I change to remove these warnings?

**Comment by bowdenk7** [comment]
Give this a shot `npm config set loglevel warn`

it isn't a solution but a workaround mentioned [here](https://github.com/npm/npm/issues/16862)
