### ISSUE TITLE
em , mongoose and connect-mongodb

### ISSUE THREAD

**Issue by edward12699** [microsoft/TypeScript-Node-Starter#122]
em.. in my project ,when i run npm run watch-debug
it will always show these errors: 
 node_modules/@types/mongoose/index.d.ts(1889,9): error TS2300: Duplicate identifier 'mquery'.
[TypeScript] node_modules/@types/mongoose/index.d.ts(1941,13): error TS2300: Duplicate identifier 'Schema'.

i've been stucked in such error for two days ,
i think it's that connect-mongo has a submodule thats install  @type/mongoose again?
that come across to the top @type/mongoose?

**Comment by orta** [comment]
I think this has been fixed, at least I could't reproduce it yesterday under a few different installation methods on Windows - so I'm going to call it good for now.
