### ISSUE TITLE
translate README.md to Chinese 🇨🇳

### ISSUE THREAD

**Issue by chinanf-boy** [Microsoft/TypeScript-Node-Starter#130]
## Would that repo like to Add a link to Chinese README.md

https://github.com/chinanf-boy/TypeScript-Node-Starter

## Or `pull` the README.zh.md file and link this

😊

**Comment by chinanf-boy** [comment]
@viveksdf how what , 🤔️?

**Comment by viveksdf** [comment]
@chinanf-boy how to add link

**Comment by chinanf-boy** [comment]
Before https://github.com/Microsoft/TypeScript-Node-Starter#pre-reqs sections

Like Add `## Translation`

```
## Translation

[中文](https://github.com/chinanf-boy/TypeScript-Node-Starter)
```

### or Plan B

> `README.zh.md` from My Pull Request

```
## Translation

[中文](https://github.com/Microsoft/TypeScript-Node-Starter/blob/master/README.zh.md)
```

**Comment by viveksdf** [comment]
@chinanf-boy Done taken your file and done a pull request on
 https://github.com/Microsoft/TypeScript-Node-Starter

**Comment by chinanf-boy** [comment]
@viveksdf Done
