### ISSUE TITLE
Not a true typescript express starter project

### ISSUE THREAD

**Issue by satya-jugran** [Microsoft/TypeScript-Node-Starter#134]
The code for app.js and server.ts should have been wrapped under classes. 

See here -> https://www.typescriptlang.org/docs/handbook/classes.html

The first example shows how a server should be initiated.

class Server {
...
...
execute = async () => {
....
}
}
const server = new Server();
server.execute(); // Thats it

Everything apart should come under classes.

**Comment by caraya** [comment]
The  beauty of Open Source... you can always create a PR and submit it when you think the code is wrong

**Comment by satya-jugran** [comment]
I am on it. will do. :)

**Comment by satya-jugran** [comment]
Create PR - https://github.com/Microsoft/TypeScript-Node-Starter/pull/136

**Comment by satya-jugran** [comment]
Changes done from my side and have submitted PR as referenced above.

**Comment by satya-jugran** [comment]
No response yet?

**Comment by havenchyk** [comment]
@bowdenk7 @DanielRosenwasser ^^

**Comment by andys8** [comment]
Official opinion is to support both functional and pop style. Where is the opinion coming from that TypeScript should be done object oriented? In terms of consistency: The application isn't using classes anywhere else.

**Comment by satya-jugran** [comment]
Hi @andys8, what you said totally makes sense.
The reasons that makes me think not to merge the OOP style is that the original repo is 
1. It is now being used by so many developers and so many forks are already there. 
2. The choice to make it OOP or functional style depends on the developers forking/cloning this project which makes it available to everyone.
The purpose of TS is to make bigger and complicated JS projects more maintainable which at-least I see is tough in the absence of object orientation.
Having said all this, what I too think is not to merge. I will keep my fork as separate under my Repo only and rename it "Typescript-Express-Starter-OOP" or something like that.

**Comment by andys8** [comment]
@satya-jugran Great to hear that. I think a OOP fork would make a nice side project and be very interesting to compare.

**Comment by BetterCallSky** [comment]
@satya-jugran 

Many people like Express because it's super simple. Currently, you added tons of abstraction that has no value — multiple classes which only wrap functions.

I recommend reading Typescript Goals https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals
> **Non-goals**
> Exactly mimic the design of existing languages. Instead, use the behavior of JavaScript and the intentions of program authors as a guide for what makes the most sense in the language.

Some developers try to code in the same way as C#, which is a wrong understanding.

**Comment by satya-jugran** [comment]
Current design makes it available to everyone (both OOP and functional style programmers), so no design changes make more sense. Closing this issue.
