### ISSUE TITLE
Link broken in the README

### ISSUE THREAD

**Issue by vajahath** [Microsoft/TypeScript-Node-Starter#14]
in the section [writing-a-dts-file](https://github.com/Microsoft/TypeScript-Node-Starter#writing-a-dts-file)

> If generating a .d.ts using dts-gen isn't working, [you should tell me about it first](https://github.com/Microsoft/TypeScript-Node-Starter/blob/master/TODO-survey-link), but then you can create your own .d.ts file.

**Comment by bowdenk7** [comment]
Fixed, thanks!
