### ISSUE TITLE
Travis Builds are broken

### ISSUE THREAD

**Issue by jarifibrahim** [microsoft/TypeScript-Node-Starter#152]
Please see https://travis-ci.org/Microsoft/TypeScript-Node-Starter/builds/441512621 and https://travis-ci.org/Microsoft/TypeScript-Node-Starter/builds/441511942

**Comment by jarifibrahim** [comment]
I can take a look at it.

**Comment by markuszm** [comment]
#154 fixes this issue

**Comment by orta** [comment]
This is now merged and CI is green 👍
