### ISSUE TITLE
You do not have permission to view this directory or page.

### ISSUE THREAD

**Issue by balajihambeere** [Microsoft/TypeScript-Node-Starter#153]
after deploying successfully while browsing the application i am getting below error

**You do not have permission to view this directory or page.**

**Comment by ahmedfarooki** [comment]
Can you specify the steps you took to replicate this?

**Comment by balajihambeere** [comment]
When i am trying to deploy in azure app service(windows) its throwing following error You do not have permission to view this directory or page.. but when i am selecting new its creating new app service plan "appsvc_asp_linux_centralus" and its working greate
