### ISSUE TITLE
istanbul or?

### ISSUE THREAD

**Issue by shaunc** [Microsoft/TypeScript-Node-Starter#16]
Thank you very much for the example. Could you extend it to show best practice for code coverage?

**Comment by markmssd** [comment]
This project uses [Jest](https://facebook.github.io/jest), which already has code coverage integrated with it. All you need to do is modify your `npm test` script to run `jest --forceExit --coverage`. You might have to configure it a little further though, to excluse files form the coverage report, etc...

**Comment by shaunc** [comment]
Ah very good. For mocha I figured it out as well -- https://github.com/pana-cc/mocha-typescript/issues/36
