### ISSUE TITLE
npm install fails on node-sass binary

### ISSUE THREAD

**Issue by JohnMilazzo** [microsoft/TypeScript-Node-Starter#165]
`npm install`

> node-sass@4.7.2 install /mnt/c/devjm/typescript/miner/node_modules/node-sass
> node scripts/install.js
> 
> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-64_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/linux-x64-64_binding.node":
> HTTP error 404 Not Found

updating package.json to use ^4.10.0 seems to make life good again.

**Comment by Yonet** [comment]
Installing node-sass fixes the issue.
```
npm i node-sass --save-dev
```

**Comment by peterblazejewicz** [comment]
@Yonet 
I think there could be an issue with specific `node-sass` version - on Windows. Are you on Windows? Can you post which version was added to your local `package.json`? I'll update the dependency, as I've experienced same problem recently on Windows machine.

**Comment by Yonet** [comment]
@peterblazejewicz, I was running into other problems and I didn't have a chance to get the project to run. There wasn't any sass issues logged but I can't confirm there weren't any issues on runtime. 
node-sass version: 4.14.1

**Comment by peterblazejewicz** [comment]
thx , I've made a PR bumping with minor version, for me it's solid on Win10, compared to `4.13.*`
