### ISSUE TITLE
bson has no exported member Int32

### ISSUE THREAD

**Issue by gregbown** [microsoft/TypeScript-Node-Starter#174]
Trying to build throws the error
```
node_modules/@types/connect-mongo/node_modules/@types/mongodb/index.d.ts(24,45): error TS2305: Module '"C:/.../node_modules/@types/bson/index"' has no exported member 'Int32'.
```
Installing @types/bson 1.0.11 resolves the error

Windows 10 pro
Node 10.15.0
TypeScript 2.7

**Comment by peterblazejewicz** [comment]
This should be fixed in updated deps as the @types/mongodb dependency supports this already:
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/43de02ea1d87534427c0b1ae95e13a26d11e4e42#diff-c4368217c3da6217f635d632d0bd4c87
If the problem persists:

```bash
npm install --no-cache
```
