### ISSUE TITLE
logger old structure caused typescript error!

### ISSUE THREAD

**Issue by AhmedBHameed** [Microsoft/TypeScript-Node-Starter#177]
This is not a bug but more than fixing annoying Typescript error

The error is:

> error 'Logger' only refers to a type, but is being used as a value here.

According to the documentation of [winston](https://www.npmjs.com/package/winston) package, those steps should work fine `Tested`.

```typescript
import winston from "winston";
import { Logger } from "winston";
import { ENVIRONMENT } from "./secrets";

const logger: Logger = winston.createLogger({
    transports: [
      new winston.transports.Console({ level: process.env.NODE_ENV === "production" ? "error" : "debug" }),
      new winston.transports.File({ filename: "debug.log", level: "debug"})
    ]
  });
  if (process.env.NODE_ENV !== "production") {
    logger.debug("Logging initialized at debug level");
  }

export default logger;
```

Please correct me if something wrong.

**Comment by sebastiangug** [comment]
How do you maek this error go away?

**Comment by AhmedBHameed** [comment]
@sebastiangug Have tried my solution up ? Try to take the same code, it should fix your issue too.

**Comment by sebastiangug** [comment]
@AhmedBHameed  Ah, sorry ,forgot to update! I have used your updated code without any issues, works like a charm, thank you!
