### ISSUE TITLE
Is project still maintained?

### ISSUE THREAD

**Issue by mchelen** [microsoft/TypeScript-Node-Starter#179]
Is this project still maintained? It seems like there are a number of outstanding pull requests waiting to be merged, such as #154 which fixes the build errors and has been needing a merge since Oct 2018.

If the maintainer(s) don't have time to work on this project that is totally understandable, but please make a note of that so everyone knows not to use this codebase.

Thanks

/cc @bowdenk7

**Comment by MikeMitterer** [comment]
> If the maintainer(s) don't have time to work on this project that is totally understandable
Really??? Not for me. This is an important repo.

**Comment by musab** [comment]
...guess not?

**Comment by jocull** [comment]
Yes - this is confusing. Internally this project is still using Typescript 2.7.2 which is quite dated. I'm not sure it even compiles under Typescript 3+

**Comment by mchelen** [comment]
It looks pretty likely the project is EOL, unless someone wants to fork &
maintain it.

**Comment by bowdenk7** [comment]
Apologies everyone - I'm a bad person...

I just merged an update that updates a bunch of dependencies including TypeScript to v3.4.5. I'll be further rehydrating this repo over the next week or so to get it back to being useful again.

**Comment by mchelen** [comment]
Great to hear, no apologies necessary! Thanks for maintaining this :+1:

**Comment by orta** [comment]
It's likely that work on this repo will always be spurts of activity, (I've just handled about ~30 PRs, and slowly looking at issues too) but I don't think it's going to be totally un-maintained unless we decide to do this with the updates to the website /docs structure. So I'm going to close this issue as, "Yes, it is still maintained"
