### ISSUE TITLE
Project no longer works

### ISSUE THREAD

**Issue by notsonotso** [Microsoft/TypeScript-Node-Starter#18]
Latest version of everything (typescript 2.4.1)

Followed instructions, got to npm start, which yields

```
node_modules/@types/request/index.d.ts(66,15): error TS2430: Interface 'DefaultUriUrlRequestApi<TRequest, TOptions, TUriUrlOptions>' incorrectly extends interface 'RequestAPI<TRequest, TOptions, TUriUrlOptions>'.
  Types of property 'defaults' are incompatible.
```

**Comment by bowdenk7** [comment]
On it, give me a couple hours, thanks!

**Comment by lucky-lou** [comment]
Just pulled this down and I'm getting the same message reported above.

**Comment by lucky-lou** [comment]
Changed package.json
"@types/request": "0.0.42"
to
"@types/request": "^0.0.45"
made this error go away.

still get these errors

src/controllers/user.ts(83,77): error TS2559: Type '4' has no properties in common with type 'MinMaxOptions'.
src/controllers/user.ts(168,77): error TS2559: Type '4' has no properties in common with type 'MinMaxOptions'.
src/controllers/user.ts(248,78): error TS2559: Type '4' has no properties in common with type 'MinMaxOptions'.

**Comment by lucky-lou** [comment]
Changed these lines from
req.assert("password", "Password must be at least 4 characters long.").len(4);
to
req.assert("password", "Password must be at least 4 characters long.").len({min: 4});

**Comment by lucky-lou** [comment]
Last fixes were to add whitespace in controllers import lines and in passport config
import {Request, Response, NextFunction} from "express";
to
import { Request, Response, NextFunction } from "express";

**Comment by notsonotso** [comment]
@bowdenk7 a couple of hours? Still not working.

**Comment by markmssd** [comment]
I've installed this project just yesterday and it worked from the first try

**Comment by lucky-lou** [comment]
I would suggest you try it today. I just downloaded it and did npm install on a different machine. Get same errors. 
node_modules/@types/request/index.d.ts(66,15): error TS2430: Interface 'DefaultUriUrlRequestApi<TRequest, TOptions, TUriUrlOptions>' incorrectly extends interfa
rlOptions>'.
  Types of property 'defaults' are incompatible.
    Type '(options: TOptions) => DefaultUriUrlRequestApi<TRequest, TOptions, OptionalUriUrl>' is not assignable to type '{ (options: TOptions): RequestAPI<TRequ
: (UriOptions & TO...'.
      Type 'DefaultUriUrlRequestApi<TRequest, TOptions, OptionalUriUrl>' is not assignable to type 'RequestAPI<TRequest, TOptions, RequiredUriUrl>'.
        Types of property 'delete' are incompatible.
          Type '{ (uri: string, options?: TOptions, callback?: request.RequestCallback): TRequest; (uri: string, ...' is not assignable to type '{ (uri: string,
RequestCallback): TRequest; (uri: string, ...'. Two different types with this name exist, but they are unrelated.
            Types of parameters 'options' and 'options' are incompatible.
              Type '(UriOptions & TOptions) | (UrlOptions & TOptions)' is not assignable to type 'OptionalUriUrl & TOptions'.
                Type 'UriOptions & TOptions' is not assignable to type 'OptionalUriUrl & TOptions'.
                  Type 'UriOptions & TOptions' is not assignable to type 'OptionalUriUrl'.
                    Types of property 'uri' are incompatible.
                      Type 'string | Url' is not assignable to type 'string'.
                        Type 'Url' is not assignable to type 'string'.
src/controllers/user.ts(83,77): error TS2559: Type '4' has no properties in common with type 'MinMaxOptions'.
src/controllers/user.ts(168,77): error TS2559: Type '4' has no properties in common with type 'MinMaxOptions'.
src/controllers/user.ts(248,78): error TS2559: Type '4' has no properties in common with type 'MinMaxOptions'.

**Comment by lucky-lou** [comment]
Pulled down the latest version. Everything is now working.

**Comment by bowdenk7** [comment]
Awesome, thanks for verifying. @notsonotso sorry for the delay. Can verify all is good on your end?

**Comment by notsonotso** [comment]
@bowdenk7 works perfectly. Thanks!
