### ISSUE TITLE
tsconfig.tests.json is missing

### ISSUE THREAD

**Issue by GitTom** [microsoft/TypeScript-Node-Starter#190]
The config file 'tsconfig.tests.json' is referenced in the 'Project Structure' section of [the README](https://github.com/microsoft/TypeScript-Node-Starter/blob/master/README.md#project-structure) but the actual file is not in the repo.

**Comment by peterblazejewicz** [comment]
@GitTom 
Thanks for pointing this out! This configuraiton is now done by Jest config file (Jest natively supports TypeScript, see details in `jest.conf.js`. The docs will be changed shortly!
