### ISSUE TITLE
Update section about hosted MongDB instance

### ISSUE THREAD

**Issue by peterblazejewicz** [microsoft/TypeScript-Node-Starter#207]
I think this section in the README: https://github.com/microsoft/TypeScript-Node-Starter/blob/master/README.md#-create-a-managed-mongodb-with-mongolab should be updated. The MongoLab is now part of the MongoDB: https://blog.mlab.com/2018/10/mlab-is-becoming-a-part-of-mongodb-inc/ and its services are (or will be) migrated to MongoDB Atlas.

The section could be rewritten in a way it contains guide for:
- Azure MongoDB  in Cosmos DB:
https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-introduction
- MongoDB Atlas:
https://docs.atlas.mongodb.com/getting-started/?_ga=2.94611034.756742394.1562365402-390215511.1558272382

**Comment by orta** [comment]
👍

**Comment by diberry** [comment]
@peterblazejewicz @orta @btholt  I'm writing content for Microsoft Docs about TS, Express, Mongo/CosmosDb and VSCode Dev Containers. I would like to use this repo as the base. 

Thoughts or concerns? I would be nice if my changes to make this repo work could continue on, either as an Azureified version of this repo (maybe a diff branch), or a separate repo.

**Comment by peterblazejewicz** [comment]
@diberry nope, on the opposite! I'd try to help as much as I could to move this thing forward.
I"ve contributed to VSCode dev containers and was tinkering on applying the concept here, to minimize the hassle of settings things locally. Just keep me in the loop!

**Comment by klemensz** [comment]
As of now, free MongoDB instances at Atlas are running MongoDB 4.4. The official docs state that this requires a node.js driver version >= 3.6. ("Your M0/M2/M5 Atlas cluster(s) will be automatically upgraded from running MongoDB 4.2 to 4.4 in late January 2021.")

Currently in package-lock.json the used version is 3.2.7 (probably as a dependeny of mongoose ^5.7.5). 

So this will need an update too... Not sure if this can be done via a PR or what you would recommend.

**Comment by diberry** [comment]
Feel free to create a PR.

**Comment by klemensz** [comment]
PR is here: https://github.com/microsoft/TypeScript-Node-Starter/pull/326 (mLab -> MongoDB Atlas)

**Comment by peterblazejewicz** [comment]
closed with: ef4a264
