### ISSUE TITLE
Please replace TSlint with ESlint

### ISSUE THREAD

**Issue by felipesilvati** [microsoft/TypeScript-Node-Starter#209]
According to https://github.com/palantir/tslint/issues/4534, TSlint will be deprecated in the near future and it will be replaced with ESlint as the 'standard JavaScript and TypeScript' linter.

Please update the boiler-plate accordingly. Thank you.

**Comment by peterblazejewicz** [comment]
@felipesilvati 
This could be a long road, but let's try. I've created the #211, so if you could, please look into proposed change and post your feedback. 
Thanks!

**Comment by peterblazejewicz** [comment]
@felipesilvati Landed in the master. Current version should be polished out in near future.
