### ISSUE TITLE
How to use jest?

### ISSUE THREAD

**Issue by RevealedFrom** [microsoft/TypeScript-Node-Starter#219]
According to [jest documentation](https://jestjs.io/docs/en/getting-started.html), jest is for Javascript. To use it with TypeScript requires the installation of Babel.

Why is jest included here, and is there any instruction on how to use it?

**Comment by orta** [comment]
Jest works fine with TypeScript, see the [bottom of that page you linked to](https://jestjs.io/docs/en/getting-started#using-typescript) 👍

**Comment by orta** [comment]
Though if you look inside the [jest settings for this repo](https://github.com/microsoft/TypeScript-Node-Starter/blob/master/jest.config.js#L1 - it uses [ts-jest](https://github.com/kulshekhar/ts-jest) which doesn't require babel
