### ISSUE TITLE
Want to remove views

### ISSUE THREAD

**Issue by ckukadiya** [microsoft/TypeScript-Node-Starter#220]
Hello,

I want to remove views form this project I only need restful API.

So I removed 
`// app.set("views", path.join(__dirname, "../views"));
// app.set("view engine", "pug");` 

But it will show me an error like 

`500 Error: No default engine was specified and no extension was provided.`

**Comment by lazaro9318** [comment]
@ckukadiya Hi, that is not an error from the project, I guess you're calling the index enpoint this implement the render method from express, such method is using the template engine so you should change for `res.rend({msg: "something"});` you can find more information [here](http://expressjs.com/en/5x/api.html#res)

**Comment by phattranky** [comment]
@ckukadiya 
Please close this issue. It's not the issue of this repository. Thanks
You can check same question at this link https://stackoverflow.com/questions/25267100/how-do-i-disable-jade-template-engine-in-express-4
