### ISSUE TITLE
Fuse Node, React, ReactNative together in Typescript

### ISSUE THREAD

**Issue by shanhuiyang** [microsoft/TypeScript-Node-Starter#228]
When I was finding Typescript web app example half year ago, I got an idea why not mix TypeScript-Node-Starter, TypeScript-React-Starter, and TypeScript-React-Native-Starter together.

Then I tried my best to build such a template in Typescript and wonder if anyone would like it?

[https://github.com/shanhuiyang/TypeScript-MERN-Starter](https://github.com/shanhuiyang/TypeScript-MERN-Starter)

Any issue and comment is welcome.

**Comment by lazaridiscom** [comment]
Far (FAR) too big README (should provide just the basics to get started and see a result quickly in an adoption-test. Additional documentation is provided by linking to it).

Now, here on the tracker, you are off-topic.

I would

* close this issue
* announce and seek feedback e.g. on reddit or other similar forums.

**Comment by peterblazejewicz** [comment]
The good thing is, the TS proliferated and seems to be core part of various exciting new projects and solutions or an obvious choice for developers.

There is no good way on the GitHub at the moment to discuss something in other way than starting an issue, so please vote here:
https://github.com/dear-github/dear-github/issues/44

@shanhuiyang 
Thanks for sharing, issue will be closed, if you don't mind.
