### ISSUE TITLE
Transpile main.ts for browser and include jquery or other client libs

### ISSUE THREAD

**Issue by pradosh987** [microsoft/TypeScript-Node-Starter#275]
While the starter project works great, I am little confused about importing jQuery or other npm libraries into `main.ts` required for browser. Do we need Webpack for it so that it transpires TS files and moves it to public directory? Right now `main.ts` is in `src` folder and not copied to public directory.

**Comment by peterblazejewicz** [comment]
@pradosh987 
So this project is aligned with ideas and process setup created for this project:
https://github.com/sahat/hackathon-starter
So the client code in the `src/public` just gets transpiled using default `tsconfig.json` and `tsc` compiler into the relevant `dist` directory. No additional transpilation or module resolving, etc.
The static assets from 'src/public/js/lib/` are copied, the `.ts` from `src/public/js` are transpiled, you should see the `main.js` and `main.js.map` there after running `npm run build`

**Comment by peterblazejewicz** [comment]
Cool, so can we close that one?
