### ISSUE TITLE
Remove `chai` from devDependecies

### ISSUE THREAD

**Issue by redd29** [microsoft/TypeScript-Node-Starter#285]
There are 2 test files with the use of `chai`, which can be completely replaced by `expect` which comes bundled with `jest`.

The files currently using `expect` from `chai` are, `test/contact.test.ts` and `test/user.test.ts`.

**Comment by peterblazejewicz** [comment]
PR?, let's see in action, thanks!

**Comment by mythio** [comment]
On it :smile_cat:
