### ISSUE TITLE
README link to TypeScript Website's documentation is broken

### ISSUE THREAD

**Issue by Julien-Marcou** [microsoft/TypeScript-Node-Starter#288]
I don't know if the problem comes from the website or the README file, but the link to the TypeScript Website's documentation doesn't work :

https://github.com/microsoft/TypeScript-Node-Starter/blob/97f9dafd62d3df565616881f07bffc887b985ed6/README.md#L5

`https://www.typescriptlang.org/docs/home` => 404
`https://www.typescriptlang.org/docs/home.html` => 200

Either TypeScript website has changed its URL format to now include `.html` extension, or the link in the README isn't correct.

**Comment by peterblazejewicz** [comment]
@Julien-Marcou
Thanks for the report! This is probably due to infrastructure detail change on the MS site. Will let folks know about this.
Closed by 2cb1d526476a489a30af443e7a951b3b8e031831
