### ISSUE TITLE
None of the tests pass. 

### ISSUE THREAD

**Issue by trydalch** [microsoft/TypeScript-Node-Starter#304]
I just cloned it down, installed with yarn, and then ran `yarn test` and all 10 tests timed out.

Is this expected?

I also tried running the tests with npm, just in case, but same result.

**Comment by yipmc** [comment]
You will need to setup MongoDB before running the tests. Run a MongoDB instance locally or use a cloud instance and configure your .env file accordingly.

**Comment by peterblazejewicz** [comment]
Yes, that's correct! @yipmc thx!
