### ISSUE TITLE
Upgrade the connect-mongo package to v4

### ISSUE THREAD

**Issue by klemensz** [microsoft/TypeScript-Node-Starter#324]
Currently it uses version [jdesboeufs/connect-mongo#527f9b6cd3d95d9bcd765c9ef9f2b5705611f9f5](https://github.com/jdesboeufs/connect-mongo/commit/527f9b6cd3d95d9bcd765c9ef9f2b5705611f9f5) (which is somewhere between version 3 and 4).

The lates version 3.2 leads to compile errors, as well as version 4.4 - needs some small code changes. I will submit a pull request.

V4 migration guide: https://github.com/jdesboeufs/connect-mongo/blob/HEAD/MIGRATION_V4.md

**Comment by peterblazejewicz** [comment]
fixed in #325
