### ISSUE TITLE
Cannot GET /favicon.ico

### ISSUE THREAD

**Issue by mozgbrasil** [microsoft/TypeScript-Node-Starter#339]
Good morning my friends

I implemented this project in

https://acid-express-labs-ts.herokuapp.com/

But we see that the file "/favicon.ico" is not loaded

I even put a file in "src/public/favicon.ico"

But when building the project we see in "dist/public" the absence of this file

Thank you in advance if you can help

**Comment by mozgbrasil** [comment]
I edited the "copyStaticAssets.ts" file and added

shell.cp("-R", "src/public/favicon.ico", "dist/public/favicon.ico");

and it worked

**Comment by peterblazejewicz** [comment]
just clarification. This project has no its own `favicon.ico` in the assets. One needs to adds it to the assets thx!
