### ISSUE TITLE
Error in development mode: req.session.returnTo = req.path;

### ISSUE THREAD

**Issue by DerianCordobaPerez** [microsoft/TypeScript-Node-Starter#353]
The error occurs when I try to run in developer mode with nodemon or with ts-node-dev the project taking the index.ts file as the starting point, because the custom definition for the express-session module inside [express-session-types.d.ts](https://github.com/microsoft/TypeScript-Node-Starter/blob/master/src/types/express-session-types.d.ts).

```bash
Property 'returnTo' does not exist on type 'Session & Partial<SessionData>'.
req.session.returnTo = req.path;
```

- The scripts used within the package.json for said execution would be the following
```bash
"dev": "nodemon src/index.ts"
```

The configurations within the tsconfig.json are exactly the same, it should be noted that once compiled to javascript code it works correctly, but to extend the flexibility of the server I wanted to perform said integration with autoreload

**Comment by peterblazejewicz** [comment]
Hey, 
it means, that TS node configuration is not including 'express-session-types',
you need make sure 'express-session-types' are included in your compilation. My guess is tsc resolves 'express-session' only to 'node_modules/@types/express-session' and no declaration is read from 'express-session-types'

**Comment by DerianCordobaPerez** [comment]
Indeed, but when doing it either with typeRoot or including the types, it takes by default the ones from the types folder inside the src and not the node_modules, sometimes the express-session call inside the app.ts file has no effect because it is not callable.

When trying to do the following
```
app.use(session({
    resave: true,
    saveUninitialized: true,
    secret: SESSION_SECRET,
    store: new MongoStore({
        mongoUrl,
        mongoOptions: {
            autoReconnect: true
        }
    })
}));
```

The following error occurs, so even if the call to the types is made, the execution in development mode still does not work.
```
This expression is not callable.
```

**Comment by peterblazejewicz** [comment]
in your current project, make sure the code that augments 'express-session' (adding 'returnTo') is included, e.g. you can import this code into entry module. The case is to force 'tsc' to properly resolved 'express-session' first (@types/express-session) and next 'express-session' augmentation code. This setup has to work for both regular and 'ts-node' setup. 'ts-node'' has special syntax to resolve deps properly (e.g. to read dedicated tsconfig). I think this is the problem. The example here ('express-session-types') is use-case specific example on how to incorporate 'returnTo' property.

**Comment by DerianCordobaPerez** [comment]
Thank you very much for this resolution, indeed the solution was to force the import within the app.ts file in the following way. ❤️ 

```bash
import * as sessionTypes from './types/express-session-types';
```
