### ISSUE TITLE
Deploy on Azure Web Apps

### ISSUE THREAD

**Issue by michaellperry** [Microsoft/TypeScript-Node-Starter#36]
When I try to deploy this starter on Azure Web Apps, I get the following error on deployment:

```
Invalid start-up command "npm run build && npm run watch" in package.json. Please use the format "node <script relative path>".
Looking for app.js/server.js under site root.
Missing server.js/app.js files, web.config is not generated
```

What's the best way to do this?

**Comment by GavinPacini** [comment]
Could you try change the `start` script in `package.json` to `node dist/server.js`. This will require you have run it once locally.

Not the most elegant solution, will reply again if I think of something better.

**Comment by lzl124631x** [comment]
@michaellperry Is your problem solved?
I met the same issue. `remote: Invalid start-up command "npm run build && node app.js" in package.json. Please use the format "node <script relative path>".`
https://github.com/projectkudu/kudu/issues/2756 
@GavinPacini I have to `npm run build` first to transpile the code then `node app.js`.

**Comment by michaellperry** [comment]
I solved the problem by changing the build to use Gulp. It has diverged quite a bit from this template.
