### ISSUE TITLE
supertest tests always pass

### ISSUE THREAD

**Issue by dmt** [Microsoft/TypeScript-Node-Starter#37]
changing any of the expected status codes to other values does not seem to have any impact on whether or not the tests pass. 

Digging a bit further, I can't get any `done` callback based test to work. The only thing that seems to work right is returning the result of the expect call. (After also adjusting the supertest initialisation to point to port 3000). 

I'm new to TypeScript, Node and these test frameworks so I might just be missing something but the fact that you can change the status codes for expectations and the tests still pass seems wrong either way.

**Comment by markmssd** [comment]
I agree with you, I had to modify the way `supertest` is configured to make it work.

e.g:

```
import * as supertest from 'supertest';
import * as sinon from 'sinon';
import { Neo4J } from '../../src/db';

const app = require('../../src/server');
const agent = supertest.agent(app);

describe('Health GET /health', () => {
  it('should return 417 Failed', (done) => {
    const stub = sinon.stub(Neo4J, 'checkConnection').rejects('error');

    agent.get('/health')
      .expect(417)
      .then(() => {
        stub.restore();
        done();
      })
      .catch(error => {
        stub.restore();
        done.fail();
      });
  });
```

**Comment by markmssd** [comment]
I noticed the same behaviour!

**Comment by cto1** [comment]
Same. Also not sure if jest import is required. I tried adding callback (done) and returning the promise. Both approaches didn't resolve this issue.

A

**Comment by michalstocki** [comment]
Same to me. The issue is because the Jest API is used incorrectly.
First of all **this cannot work** because when running tests (`npm test`) there is no place where the server is set up – literally there is nothing like `http://localhost:8000` because there is no such server.
Moving further, all the tests incorrectly uses the Jest `done()` callback. As long as in Mocha or Jasmine, we can simply call `done(err)` to make the test fail, in Jest we must call `done.fail(err)` instead.

So, after replacing:
```typescript
    request.get("/contact")
      .expect(200, done);
```
with
```typescript
    request.get("/contact")
      .expect(200, (err, res) => {
        if (err) {
          done.fail(err);
        } else {
          done();
        }
      });
```
or better with
```typescript
    request.get("/contact")
      .expect(200)
      .end((err, res) => {
        if (err) {
          done.fail(err);
        } else {
          done();
        }
      });
```
all the tests fail.
At the end I must say, that I spend several hours trying to figure out how the tests are configured that they work, without any configuration of the server under `localhost:8000`, so I'm a bit frustrated. 😞

**Comment by michalstocki** [comment]
BTW @dmt that's why after your change, the tests are failing in #38

**Comment by dmt** [comment]
It's possible to `return` the result of setting up the expectation and that seems to behave as it should. I did also update the PR to separate the setup of the app and actually binding to the port. This does make it possible to run the tests, requiring that extracted app setup instead of assuming there is an instance of the server running somewhere. 

I'm still not super happy with the changes for various design reasons and the fact that I don't actually know anything about typescript. But at least the tests now actually do something.

**Comment by welkie** [comment]
This has to do with how Promises are used in JavaScript tests. If you're testing something asynchronous, you must return a promise from the callback in the `it` function. Alternatively, you add a `done` parameter and call it at the end of the test. Note that some asynchronous tests will need longer than the default time limit most testing frameworks allow per test, so it's normal to increase that time limit for them.
