### ISSUE TITLE
MongoError: not authorized on admin to execute command { listIndexes: "sessions", cursor: {} }

### ISSUE THREAD

**Issue by JohnReedLOL** [Microsoft/TypeScript-Node-Starter#39]
I installed Mongo according to the instructions at: https://www.howtoforge.com/tutorial/install-mongodb-on-ubuntu-16.04/ and I am getting an error.

[Node] Unhandled rejection MongoError: not authorized on admin to execute command { listIndexes: "sessions", cursor: {} }
[Node]     at Function.MongoError.create (/home/ubuntu/projects/project2/node_modules/mongodb-core/lib/error.js:31:11)
[Node]     at queryCallback (/home/ubuntu/projects/project2/node_modules/mongodb-core/lib/cursor.js:212:36)
[Node]     at /home/ubuntu/projects/project2/node_modules/mongodb-core/lib/connection/pool.js:469:18
[Node]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[Node]     at process._tickCallback (internal/process/next_tick.js:180:9)
[Node] [nodemon] restarting due to changes...
[Node] [nodemon] restarting due to changes...
[Node] [nodemon] starting `node dist/server.js`
[Node] [nodemon] restarting due to changes...
[Node] [nodemon] restarting due to changes...
[Node] [nodemon] restarting due to changes...
[Node] [nodemon] starting `node dist/server.js`
[Node] [nodemon] restarting due to changes...
[Node] [nodemon] restarting due to changes...
[Node] [nodemon] restarting due to changes...
[TypeScript] 19:39:18 - Compilation complete. Watching for file changes.
[TypeScript] 
[TypeScript] 
[Node] [nodemon] starting `node dist/server.js`
[Node]   App is running at http://localhost:3000 in development mode
[Node]   Press CTRL-C to stop
[Node] 
[Node] Unhandled rejection MongoError: not authorized on admin to execute command { listIndexes: "sessions", cursor: {} }
[Node]     at Function.MongoError.create (/home/ubuntu/projects/project2/node_modules/mongodb-core/lib/error.js:31:11)
[Node]     at queryCallback (/home/ubuntu/projects/project2/node_modules/mongodb-core/lib/cursor.js:212:36)
[Node]     at /home/ubuntu/projects/project2/node_modules/mongodb-core/lib/connection/pool.js:469:18
[Node]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[Node]     at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by JohnReedLOL** [comment]
Sorry for bugging you, but I am trying to learn the basics and don't want the database roles to get in my way. Is there any way to grant all privileges to admin and not have to worry about authorization errors?

**Comment by BKeanu1989** [comment]
I know this is closed, but all of a sudden (server unexpected shutdown) I get the same error.
Did u come to a solution?

**Comment by kirtanshetty** [comment]
Did you guys every find a solution for this ?
