### ISSUE TITLE
Bug in controllers/user.ts

### ISSUE THREAD

**Issue by BobAvatar** [Microsoft/TypeScript-Node-Starter#4]
Problem: Messages `Email ${email} not found.` and "Invalid email or password." do not show up.
Solution: Line 44 in controllers/user.ts should be
`      req.flash("errors", { msg: info.message });`
instead of
`      req.flash("errors", info );`

**Comment by maxpaynestory** [comment]
I think this mistake is inside whole project.

**Comment by bowdenk7** [comment]
Hi @maxpaynestory - I fixed @BobAvatar's original issue (thanks!) but what do you mean this issue is inside the whole project?

**Comment by maxpaynestory** [comment]
req.flash(arge1,arg2) takes two arguments and both of them need to be a string. Its mistaken on many places inside the source code. e.g

https://github.com/Microsoft/TypeScript-Node-Starter/blob/master/src/controllers/user.ts#L102
