### ISSUE TITLE
[Question] Without node_modules folder, dist/server.js doesn't work

### ISSUE THREAD

**Issue by paibamboo** [Microsoft/TypeScript-Node-Starter#49]
Is there any way to compile it using `tsc` so that modules which files in src folder import get bundled in the dist folder too?

**Comment by snawar92** [comment]
@paibamboo if you are thinking of not using typescript ... then why are you trying to use this kick starter ... you should go for othrt kickstarter .... think twice you could doo better code with typescript

**Comment by devnetics** [comment]
http://lmgtfy.com/?q=tsc+output+dir+node_modules

**Comment by devnetics** [comment]
You have to do it manually (or with your own script).

**Comment by bowdenk7** [comment]
Sorry for the long delay, but what is the motivation behind this? Sure you could bundle and move things around with webpack, but I'm not sure what the benefit is. I would be against adding more tools and complexity unless there are some solid benefits.

**Comment by paibamboo** [comment]
I now think having to rely on `dist` folder on Node is fine, it's not a browser environment that we have to bundle everything as minimal as possible in one file.
