### ISSUE TITLE
Debug TypeScript sources in VS Code

### ISSUE THREAD

**Issue by Deilan** [Microsoft/TypeScript-Node-Starter#5]
Right now there's no capability to debug TypeScript source code in VS Code. So it would be great to implement it.

**Comment by bowdenk7** [comment]
Hi @Deilan - debugging TypeScript works for me. You do have to shut down any running instance from command line and launch the app through VS Code (F5) in debug mode though. Does that not work for you?

**Comment by Deilan** [comment]
If I run debug right from the start, I receive an error `Attribute 'program' does not exist ('c:\Dev\TypeScript-Node-Starter/dist/server.js.js').`. If I run `npm start` and then launch debug, I receive `EADDRINUSE` error. After some experimenting I found out that one need to run `build` and launch debug after that. That wasn't very obvious for me at the beginning. :)

**Comment by bowdenk7** [comment]
That's a great point actually. I'll add a note the debugging session in the README to make sure the project has been built once already. I'm working on trying to consolidate everything to run on F5 in VS Code but am not quite there yet. 

Thanks again for the feedback and please let me know if there is anything else you think I can do to make this starter guide more helpful!

**Comment by Deilan** [comment]
@bowdenk7 Thanks for such a fast feedback! No worries, I've submitted a pull request #7 which closes the issue. Now the build task will launch automatically before starting debugging session. Hope it helps us all. :)

**Comment by bowdenk7** [comment]
Thanks @Deilan!
