### ISSUE TITLE
mongo steps

### ISSUE THREAD

**Issue by Bigbrd** [Microsoft/TypeScript-Node-Starter#62]
For users who are just setting up mongo, they cant just run 'mongod', they run into errors. It's worth calling out that they first needed to run:
`sudo mkdir -p /data/db` //this creates the db directory
`sudo chmod 777 /data/db` //this gives the db correct read/write permissions

Before they can get up and go. Worth putting in for saving other newbies a few stackoverflow searches.

Sources:
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/
https://stackoverflow.com/questions/28987347/setting-read-write-permissions-on-mongodb-folder/29003511

**Comment by tioback** [comment]
@Bigbrd - I added a pull request #79 with suggested changes.

Hopefully the maintainers will accept it and merge to master.

Cheers

**Comment by bowdenk7** [comment]
Fixed in #79 - thanks all!
