### ISSUE TITLE
problem with npm start

### ISSUE THREAD

**Issue by Spandana-Gajangi** [Microsoft/TypeScript-Node-Starter#65]
Its not creating dist folder when I use npm start.
got an error that "Error: Cannot find module 'C:\Users\TypeScript-Node-Starter-master\dist\server.js'"
when start debugging in VS got an error that "Debugging with legacy protocol because Node.js version could not be determined (Error: connect ECONNREFUSED 127.0.0.1:9229)"

**Comment by dorongrinstein** [comment]
It seems to be missing **npm run build** before npm start

**Comment by Spandana-Gajangi** [comment]
How to debug typescript code in visualstudio or in someother IDE. 
When I try to debug its saying that try in legacy mode but in latest versions of VS there is no legacy mode.

**Comment by bowdenk7** [comment]
Both of these issues are now fixed. Trying pulling and trying again. Thanks for the feedback!
