### ISSUE TITLE
adding new modules

### ISSUE THREAD

**Issue by Spandana-Gajangi** [Microsoft/TypeScript-Node-Starter#72]
I have a problem with adding new npm modules like method-override, helmet and winston-express-middleware
I tried adding new modules with npm install --save @types/winnston-express-middleware
but there is an npm Error: "npm ERR! 404 Not Found: @types/winston-express-middleware@latest"
 "[ts] Could not find a declaration file for module 'winnston-express-middleware'.
" error TS7016: Could not find a declaration file for module 'winston-express-middleware'."
these is the case the all modules I tried to add.

**Comment by bowdenk7** [comment]
Hi @Spandana-Gajangi, you need `.d.ts` files for each new module you add. Does [this](https://github.com/Microsoft/TypeScript-node-Starter/#type-definition-dts-files) section in the README help?
