### ISSUE TITLE
Why use module.exports over export

### ISSUE THREAD

**Issue by aaroncolaco** [Microsoft/TypeScript-Node-Starter#83]
In [app.ts](https://github.com/Microsoft/TypeScript-Node-Starter/blob/master/src/app.ts#L122) is there a reason to use
```
module.exports = {} 
```
over Typescript's
```
export {}
```

**Comment by MPankajArun** [comment]
Well, “exports” itself is never returned! It is just a reference to module.exports; a convenience variable to help module authors write less code.

**Comment by peterblazejewicz** [comment]
@aaroncolaco 
I've added PR with TS2.7 and ECMA script modules support enabled: #85

**Comment by aaroncolaco** [comment]
@peterblazejewicz awesome! Thanks.
