### ISSUE TITLE
Issue with WebStorm with "esModuleInterop": true

### ISSUE THREAD

**Issue by welkie** [Microsoft/TypeScript-Node-Starter#96]
I noticed this a few days ago when exploring using WebStorm. Previously, I had used Visual Studio Code with this starter repo's `tsconfig.json` file. Everything worked fine. But in order for WebStorm's "compile typescript" pre-launch task to work, I had to remove the `"esModuleInterop": true` property from this `tsconfig.json` file (and return to using the `import * as x from 'y';` import style instead of the `import x from 'y';` style that this property allowed. In WebStorm, before removing this property, the compile step is skipped, and the launch task attempts to run and then fails since the `dist` directory is still empty (no compilation occurred).

**Comment by bowdenk7** [comment]
Are you able to specify which version of TypeScript that WebStorm uses to compile? Seems like they don't have support for 2.7?

**Comment by welkie** [comment]
I was setting WebStorm to use the TypeScript compiler in my project, which was 2.7.2. Their website claims that it supports 2.7, but they actually had this bug I'm referring to logged about a month or two ago. So it looks like this is a bug in WebStorm right now which is hopefully somewhere on their road map to fix.

A workaround is to just go back to the old style of importing CommonJS modules.

**Comment by bowdenk7** [comment]
Might work if you give their latest [Release Candidate](http://www.jetbrains.com/webstorm/nextversion/#typescript) a shot. 

Just curious, is there anything in particular that makes you choose WebStorm, or is it just personal preference?

**Comment by welkie** [comment]
Stronger Intellisense in some situations, refactoring tools etc. Though I haven't committed to using WebStorm over free tools. I was just exploring it. Right now, friction like that was enough to turn me off. I find with Visual Studio Code, I feel less pressure to do things "the JetBrains way". WebStorm wanted me to arrange my build process according to their liking, complaining if files to run after the build aren't there yet (duh, I haven't built yet) and so I'm sticking with Visual Studio Code for now, which seems to break things down into smaller steps that I can manually perform (do a build, then do a run, etc).

**Comment by vadikace** [comment]
Disabling checkbox "Also for projects without tsconfig.json" in _Settings > Languages & Frameworks > Typescript_ seems to help.

**Comment by peterblazejewicz** [comment]
for reference, original issues was related to WebStorm, see their blog post comments:
https://blog.jetbrains.com/webstorm/2016/03/how-to-compile-typescript-in-webstorm/#comment-315741
